### ISSUE TITLE
API Docs and DB Diagram

### ISSUE THREAD

**Issue by irelius** [AnthonyBotha/AntBnB#1]
# DB Diagram
The dbdiagram should be properly referenced in your README so that it displays the image and not a link (the link is also broken, probably why it doesn't work). The diagram also has some issues, especially with how the relationships are drawn out.

## Tasks
- [ ] The Users table is missing a column. Refer to the API docs for a clue
- [ ] Remove the Owners table. The Users tables should be the only table that contains information about the user
- [ ] When you remove the Owners table, you'll also need to revise where the "ownerId" column under the Spots table is related to
- [ ] Remove the relationship between "name" and "lng" under the Spots table
- [ ] There is no relationship between Spots and SpotImages
- [ ] There is no relationship between Spots and Bookings
- [ ] There is no relationship between Reviews and ReviewImages
- [ ] "avgRating" under Spots is not necessary
- [ ] "previewImage" under Spots is not necessary. You should instead specify if an image is a preview image under the SpotImages table. This is because Airbnb has multiple preview images, not just one

# API Docs
The rest of the API docs will need to be filled out. There are a couple things to fix with the current routes as well

## Tasks
- [ ] Route for "Get the Current User" is not ideal. Route includes the parameter ":id" which implies that you could use this route to get information for any user given any id. You want this route to only get information for the current user
- [ ] Route for "Get all Spots owned by the Current User" is not ideal. See above for more information. The route is also the same as the route for "Get details of a Spot from an id", even if the parameters are written differently.
- [ ] Route for adding a image to a spot is not complete. How do you know which spot you'll be adding the image to?
- [ ] Edit a Spot method and URL required
- [ ] Delete a Spot method and URL required
- [ ] Get all Reviews of Current User method and URL required
- [ ] Get All Reviews by a Spot's id method and URL required
- [ ] Create a review for Spot method and URL required
- [ ] Add an Image to a Review method and URL required
- [ ] Edit a Review method and URL required
- [ ] Delete a Review method and URL required
- [ ] Get all Current User Bookings method and URL required
- [ ] Get all Bookings for Spot method and URL required
- [ ] Create a Booking for Spot method and URL required
- [ ] Edit a Booking method and URL required
- [ ] Delete a Booking method and URL required
- [ ] Delete a Spot Image method and URL required
- [ ] Delete a Review Image method and URL required
- [ ] Add Query Filters to Get All Spots method and URL required

# Deadline
Please complete the rest of your API docs and make the edits to the DBDiagram tasks by EOD on Monday May, 13th. We are looking to get these documents finalized so we can move forward to the next phase of the project life cycle the following day.

**Comment by irelius** [comment]
# API Docs and DB Diagram Review 2

## DB Diagram
Looks great! Good work.

## API Docs
- [ ] Route for "Get all Spots owned by the Current User" should follow this hierarchy if following restful conventions: `<parents>/<:parentId>/<child>/<:childId>`. Your route currently has everything it needs, you just want to rearrange the order a little bit
- [ ] Route for "Add an Image to a Spot" has similar issue as point above
- [ ] Route for "Get all Reviews of the Current User" has similar issue as point above
- [ ] Route for "Get all Reviews by a Spot's id" needs refactoring. You getting all of the reviews that belong to a particular spot
- [ ] Route for "Create a Review for a Spot based on the Spot's id" needs rearranging in its order. There is also a typo in the route
- [ ] Route for "Edit a Review" has an unnecessary component to the route
- [ ] Route for "Delete a Review" has similar issue as point above
- [ ] Route for "Get all of the Current User's Bookings" needs rearranging
- [ ] Route for "Get all Bookings by a Spot's id" needs refactoring. You getting all of the bookings that belong to a particular spot
- [ ] Route for "Create a Booking for a Spot" has an unnecessary component in the API endpoint
- [ ] Route for "Edit a Booking" has an unnecessary component in the API endpoint
- [ ] Route for "Delete a Booking" has an unnecessary component in the API endpoint
- [ ] Route for "Delete a Spot Image" needs refactoring. You are trying to delete a spot's image. Note that a spot could have many images
- [ ] Route for "Delete a Review Image" needs refactoring. You are trying to delete a review's image. Note that a review could have many images
- [ ] Route for "Add Query Filters" needs refactoring. The route currently uses ":" which indicates parameters. You want to use queries
- [ ]

**Comment by irelius** [comment]
API Docs and DB Diagram Review 3

## DB Diagram
- [ ] Didn't notice this before, but the "price" data type under Spots should be decimal, not integer
- [ ] You'll also want to change "password" under Users to be "hashedPassword". This is to make it more clear that we're storing the password after it's been salted and hashed. We never want to store plain text passwords in our database

## API Docs
- [ ] "Sign Up a User" endpoint should be "/api/signup". Log in and sign up functionalities are a bit unique in their api endpoint naming schemes, they don't really follow the traditional restful convention as they're more to do with authentication
- [ ] "Get all Bookings for a Spot based on the Spot's id" should be refactored. The route does not need to include "users". While restful conventions has you write out routes going from parent to child, you don't need to include "grandparents" in the routes. The route also needs to be reordered
- [ ] "Delete a Spot Image" endpoint is similar to above; it doesn't need to include "users" in the routes as Users is the grandparent of images. The route also needs to be reordered (the id parameter should come directly after the table it's an id for)
